"""Phase 5b optional de novo repeat-annotation planning and provenance."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import logging
from pathlib import Path

from .schemas import (
    PHASE5B_OUTPUT_INVENTORY_COLUMNS,
    PHASE5B_PLAN_COLUMNS,
    PHASE5B_PREFLIGHT_COLUMNS,
    PHASE5B_PROVENANCE_COLUMNS,
)
from .utils import read_yaml, write_tsv

LOGGER = logging.getLogger(__name__)
NOT_ASSESSED = "NOT_ASSESSED"
TODO = "TODO"


def file_hash(path: Path, algorithm: str) -> str:
    digest = hashlib.new(algorithm)
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def bool_status(value: bool) -> str:
    return "PASS" if value else "FAIL"


def gzip_status(path: Path) -> str:
    if not path.exists():
        return "NOT_ASSESSED"
    if not path.name.endswith(".gz"):
        return "PLAIN_FASTA_OR_UNKNOWN"
    try:
        with gzip.open(path, "rb") as handle:
            handle.read(4096)
        return "READABLE_GZIP"
    except OSError:
        return "UNREADABLE_GZIP"


def phase5b_config(config: dict) -> dict:
    return config.get("phase5b_repeat_annotation", {})


def configured_path(value: str | None) -> Path:
    if not value:
        return Path("")
    return Path(value)


def build_preflight_rows(config: dict) -> list[dict[str, str]]:
    phase = phase5b_config(config)
    genome = configured_path(phase.get("genome_fasta"))
    work_dir = configured_path(phase.get("work_dir", "data/interim/repeats/phase5b"))
    output_dir = configured_path(phase.get("output_dir", "results/repeats/phase5b"))
    repeatmasker_gff = configured_path(phase.get("repeatmasker_gff", "results/repeats/phase5b/smic_tokyo.repeatmasker.out.gff"))
    repeatmasker_out = configured_path(phase.get("repeatmasker_out", "results/repeats/phase5b/smic_tokyo.repeatmasker.out"))
    custom_library = configured_path(phase.get("custom_library", "results/repeats/phase5b/smic_tokyo-families.fa"))
    container_image = str(phase.get("container_image", TODO))
    container_digest = str(phase.get("container_resolved_digest", ""))

    rows = [
        {
            "check_id": "PHASE5B-GENOME-FASTA",
            "resource": "SMIC_TOKYO_GENOME_2025",
            "path_or_setting": str(genome),
            "status": bool_status(genome.exists()),
            "required_for": "RepeatModeler and RepeatMasker external run",
            "details": f"gzip_status={gzip_status(genome)};byte_size={genome.stat().st_size if genome.exists() else NOT_ASSESSED}",
            "notes": "Use the exact Tokyo/PNAS genome FASTA registered in config. Keep raw FASTA immutable; stage any decompressed copy under data/interim/.",
        },
        {
            "check_id": "PHASE5B-WORK-DIR",
            "resource": "local_workspace",
            "path_or_setting": str(work_dir),
            "status": "PASS",
            "required_for": "External run staging",
            "details": "Directory may be created by the external command.",
            "notes": "This directory is ignored by Git through data/interim/.",
        },
        {
            "check_id": "PHASE5B-OUTPUT-DIR",
            "resource": "local_workspace",
            "path_or_setting": str(output_dir),
            "status": "PASS",
            "required_for": "External run outputs",
            "details": "Directory may be created by the external command.",
            "notes": "This directory is ignored by Git through results/.",
        },
        {
            "check_id": "PHASE5B-CONTAINER-IMAGE",
            "resource": "container_runtime",
            "path_or_setting": container_image,
            "status": "PASS" if container_digest else ("WARN" if container_image in {"", TODO, "dfam/tetools:latest"} else "PASS"),
            "required_for": "Docker route",
            "details": (
                f"resolved_digest={container_digest}"
                if container_digest
                else "Container image should be pinned to a tested tag before production repeat annotation."
            ),
            "notes": "A moving latest tag is acceptable for exploration only if the resolved digest/version is recorded afterward.",
        },
        {
            "check_id": "PHASE5B-REPEATMODELER-LIBRARY",
            "resource": "external_output",
            "path_or_setting": str(custom_library),
            "status": "PRESENT" if custom_library.exists() else "EXPECTED_NOT_PRESENT",
            "required_for": "RepeatMasker with species-specific library",
            "details": f"byte_size={custom_library.stat().st_size if custom_library.exists() else NOT_ASSESSED}",
            "notes": "This file is generated by RepeatModeler and should be retained with provenance.",
        },
        {
            "check_id": "PHASE5B-REPEATMASKER-GFF",
            "resource": "external_output",
            "path_or_setting": str(repeatmasker_gff),
            "status": "PRESENT" if repeatmasker_gff.exists() else "EXPECTED_NOT_PRESENT",
            "required_for": "Phase 5 repeat-context reanalysis",
            "details": f"byte_size={repeatmasker_gff.stat().st_size if repeatmasker_gff.exists() else NOT_ASSESSED}",
            "notes": "When present, add this path to phase5_repeat_context.repeat_annotation_candidates and rerun Phase 5.",
        },
        {
            "check_id": "PHASE5B-REPEATMASKER-OUT",
            "resource": "external_output",
            "path_or_setting": str(repeatmasker_out),
            "status": "PRESENT" if repeatmasker_out.exists() else "EXPECTED_NOT_PRESENT",
            "required_for": "RepeatMasker raw interval provenance",
            "details": f"byte_size={repeatmasker_out.stat().st_size if repeatmasker_out.exists() else NOT_ASSESSED}",
            "notes": "The GFF output is preferred for Phase 5 import; the .out file is retained as raw RepeatMasker evidence.",
        },
    ]
    return rows


def powershell_path(path: str) -> str:
    return path.replace("\\", "/")


def build_plan_rows(config: dict) -> list[dict[str, str]]:
    phase = phase5b_config(config)
    genome = str(phase.get("genome_fasta", "data/raw/references/SMIC_TOKYO_GENOME_2025/GCA_056099535.1_ASM5609953v1_genomic.fna.gz"))
    work_dir = str(phase.get("work_dir", "data/interim/repeats/phase5b"))
    output_dir = str(phase.get("output_dir", "results/repeats/phase5b"))
    staged_genome = str(phase.get("staged_genome_fasta", "data/interim/repeats/phase5b/smic_tokyo_genome.fna"))
    db_name = str(phase.get("database_name", "smic_tokyo"))
    custom_library = str(phase.get("custom_library", "results/repeats/phase5b/smic_tokyo-families.fa"))
    repeatmasker_gff = str(phase.get("repeatmasker_gff", "results/repeats/phase5b/smic_tokyo.repeatmasker.out.gff"))
    repeatmasker_out = str(phase.get("repeatmasker_out", "results/repeats/phase5b/smic_tokyo.repeatmasker.out"))
    repeatmasker_dir = str(phase.get("repeatmasker_output_dir", "results/repeats/phase5b/repeatmasker_raw"))
    image = str(phase.get("container_image", "dfam/tetools:latest"))
    builddatabase = str(phase.get("builddatabase_executable", "BuildDatabase"))
    repeatmodeler = str(phase.get("repeatmodeler_executable", "RepeatModeler"))
    repeatmasker = str(phase.get("repeatmasker_executable", "RepeatMasker"))
    threads = str(phase.get("threads", 8))
    docker_prefix = f'docker --context desktop-linux run --rm -v "${{repo}}:/work" -w /work {image}'
    docker_bash = f'{docker_prefix} bash -lc'
    rows = [
        {
            "step_id": "01",
            "step_name": "Create ignored work and output directories",
            "recommended_environment": "PowerShell host",
            "command_template": f"New-Item -ItemType Directory -Force {work_dir}, {output_dir}, {repeatmasker_dir}",
            "expected_output": f"{work_dir};{output_dir};{repeatmasker_dir}",
            "run_status": "MANUAL_OPTIONAL_NOT_RUN_BY_REPO",
            "notes": "Directories are under ignored data/interim and results paths.",
        },
        {
            "step_id": "02",
            "step_name": "Stage uncompressed genome FASTA",
            "recommended_environment": "PowerShell or WSL/Linux",
            "command_template": f"gzip -dc {powershell_path(genome)} > {powershell_path(staged_genome)}",
            "expected_output": staged_genome,
            "run_status": "MANUAL_OPTIONAL_NOT_RUN_BY_REPO",
            "notes": "Keep the raw .gz immutable. RepeatModeler/RepeatMasker runs should use a staged copy.",
        },
        {
            "step_id": "03",
            "step_name": "Build RepeatModeler database",
            "recommended_environment": "Docker desktop-linux or WSL/Linux",
            "command_template": f'{docker_bash} "cd {powershell_path(work_dir)} && {builddatabase} -name {db_name} smic_tokyo_genome.fna"',
            "expected_output": f"{db_name}.* database files in {work_dir}",
            "run_status": "MANUAL_OPTIONAL_NOT_RUN_BY_REPO",
            "notes": "Run from a clean Phase 5b work directory. Record container digest and tool versions after the run.",
        },
        {
            "step_id": "04",
            "step_name": "Run RepeatModeler",
            "recommended_environment": "Docker desktop-linux or WSL/Linux",
            "command_template": f'{docker_bash} "cd {powershell_path(work_dir)} && {repeatmodeler} -database {db_name} -threads {threads} -LTRStruct && cp RM_*/consensi.fa.classified /work/{powershell_path(custom_library)}"',
            "expected_output": custom_library,
            "run_status": "MANUAL_OPTIONAL_NOT_RUN_BY_REPO",
            "notes": "RepeatModeler 2.0.8 uses -threads; the species-specific family library should be copied or symlinked to the configured custom_library path.",
        },
        {
            "step_id": "05",
            "step_name": "Run RepeatMasker with custom library and GFF output",
            "recommended_environment": "Docker desktop-linux or WSL/Linux",
            "command_template": f'{docker_bash} "{repeatmasker} -pa {threads} -lib {powershell_path(custom_library)} -gff -xsmall -dir {powershell_path(repeatmasker_dir)} {powershell_path(staged_genome)} && cp {powershell_path(repeatmasker_dir)}/smic_tokyo_genome.fna.out.gff {powershell_path(repeatmasker_gff)} && cp {powershell_path(repeatmasker_dir)}/smic_tokyo_genome.fna.out {powershell_path(repeatmasker_out)}"',
            "expected_output": f"{repeatmasker_gff};{repeatmasker_out}",
            "run_status": "MANUAL_OPTIONAL_NOT_RUN_BY_REPO",
            "notes": "Do not interpret repeat overlap biologically. RepeatMasker output is artifact/context evidence for candidate-locus review.",
        },
        {
            "step_id": "06",
            "step_name": "Record repeat-output checksums",
            "recommended_environment": "green_shark Python environment",
            "command_template": "python -m greenland_shark_longevity.phase5b_repeat_annotation --config config/config.yaml --preflight-output results/repeats/phase5b_repeat_annotation_preflight.tsv --plan-output results/repeats/phase5b_repeat_annotation_plan.tsv --provenance-output data/metadata/phase5b_repeat_annotation_provenance.tsv --output-inventory data/metadata/phase5b_repeat_output_inventory.tsv",
            "expected_output": "data/metadata/phase5b_repeat_output_inventory.tsv",
            "run_status": "READY_AFTER_EXTERNAL_RUN",
            "notes": "This repository command is lightweight and records whether expected repeat outputs exist.",
        },
        {
            "step_id": "07",
            "step_name": "Reanalyze candidate repeat context",
            "recommended_environment": "green_shark Python environment",
            "command_template": f"Add {repeatmasker_gff} to phase5_repeat_context.repeat_annotation_candidates, then rerun python -m greenland_shark_longevity.phase5_repeat_context ...",
            "expected_output": "results/repeats/phase5_candidate_locus_repeat_context.tsv;results/repeats/phase5_gene_repeat_context_summary.tsv",
            "run_status": "READY_AFTER_REPEATMASKER_GFF_EXISTS",
            "notes": "This reuses the existing Phase 5 parser/intersection and keeps repeat context separate from biological claims.",
        },
    ]
    return rows


def build_provenance_rows(config: dict) -> list[dict[str, str]]:
    phase = phase5b_config(config)
    rows = [
        ("analysis_id", "PHASE5B_DE_NOVO_REPEAT_ANNOTATION", "REGISTERED", "Optional workflow for de novo repeat annotation and candidate-locus reanalysis."),
        ("resource_id", "SMIC_TOKYO_GENOME_2025", "REGISTERED", "Tokyo/PNAS assembly used for repeat annotation."),
        ("genome_fasta", str(phase.get("genome_fasta", TODO)), "REGISTERED", "Input genome FASTA. Raw input must remain immutable."),
        ("container_image", str(phase.get("container_image", TODO)), "REGISTERED", "Container image used for the Docker route."),
        ("container_resolved_digest", str(phase.get("container_resolved_digest", TODO)), "REGISTERED" if phase.get("container_resolved_digest") else "TODO", "Resolved image digest observed during Docker preflight."),
        ("container_verified_at", str(phase.get("container_verified_at", TODO)), "REGISTERED" if phase.get("container_verified_at") else "TODO", "Date when container availability and tool paths were checked."),
        ("builddatabase_executable", str(phase.get("builddatabase_executable", "BuildDatabase")), "REGISTERED", "Executable path used inside the container."),
        ("repeatmodeler_executable", str(phase.get("repeatmodeler_executable", "RepeatModeler")), "REGISTERED", "Executable path used inside the container."),
        ("repeatmasker_executable", str(phase.get("repeatmasker_executable", "RepeatMasker")), "REGISTERED", "Executable path used inside the container."),
        ("repeatmodeler_version", str(phase.get("repeatmodeler_version", TODO)), "REGISTERED" if phase.get("repeatmodeler_version") else "TODO", "Observed from external container preflight."),
        ("repeatmasker_version", str(phase.get("repeatmasker_version", TODO)), "REGISTERED" if phase.get("repeatmasker_version") else "TODO", "Observed from external container preflight."),
        ("repeatmasker_database", str(phase.get("repeatmasker_database", TODO)), "TODO", "Record Dfam/RepBase/custom library state where applicable."),
        ("custom_library", str(phase.get("custom_library", TODO)), "EXPECTED", "Species-specific library generated by RepeatModeler."),
        ("repeatmasker_gff", str(phase.get("repeatmasker_gff", TODO)), "EXPECTED", "Preferred import file for Phase 5 interval intersection."),
        ("interpretation_policy", "artifact_context_only", "REGISTERED", "Repeat overlap is not mechanism, adaptation, duplication, or longevity evidence by itself."),
    ]
    return [{"field": field, "value": value, "status": status, "notes": notes} for field, value, status, notes in rows]


def build_output_inventory_rows(config: dict) -> list[dict[str, str]]:
    phase = phase5b_config(config)
    outputs = [
        ("repeatmodeler_library", "custom_repeat_library", phase.get("custom_library", "results/repeats/phase5b/smic_tokyo-families.fa"), "false", "Generated by RepeatModeler; used as RepeatMasker input."),
        ("repeatmasker_gff", "repeat_annotation_gff", phase.get("repeatmasker_gff", "results/repeats/phase5b/smic_tokyo.repeatmasker.out.gff"), "true", "Preferred Phase 5 import once present."),
        ("repeatmasker_out", "repeatmasker_raw_out", phase.get("repeatmasker_out", "results/repeats/phase5b/smic_tokyo.repeatmasker.out"), "false", "Raw RepeatMasker interval table retained for provenance."),
        ("repeatmasker_tbl", "repeatmasker_summary_table", phase.get("repeatmasker_tbl", "results/repeats/phase5b/smic_tokyo.repeatmasker.tbl"), "false", "Genome-wide repeat class summary if produced."),
    ]
    rows: list[dict[str, str]] = []
    for output_id, role, path_value, import_flag, notes in outputs:
        path = Path(str(path_value))
        exists = path.exists()
        rows.append(
            {
                "output_id": output_id,
                "file_role": role,
                "local_path": str(path),
                "status": "LOCAL_AVAILABLE" if exists else "EXPECTED_NOT_PRESENT",
                "byte_size": str(path.stat().st_size) if exists else NOT_ASSESSED,
                "md5": file_hash(path, "md5") if exists else NOT_ASSESSED,
                "sha256": file_hash(path, "sha256") if exists else NOT_ASSESSED,
                "recommended_for_phase5_import": import_flag,
                "notes": notes,
            }
        )
    return rows


def write_phase5b_tables(
    config_path: Path,
    preflight_output: Path,
    plan_output: Path,
    provenance_output: Path,
    output_inventory: Path,
) -> None:
    config = read_yaml(config_path)
    write_tsv(preflight_output, build_preflight_rows(config), PHASE5B_PREFLIGHT_COLUMNS)
    write_tsv(plan_output, build_plan_rows(config), PHASE5B_PLAN_COLUMNS)
    write_tsv(provenance_output, build_provenance_rows(config), PHASE5B_PROVENANCE_COLUMNS)
    write_tsv(output_inventory, build_output_inventory_rows(config), PHASE5B_OUTPUT_INVENTORY_COLUMNS)
    LOGGER.info("Wrote Phase 5b repeat-annotation planning/provenance tables")


def main() -> None:
    parser = argparse.ArgumentParser(description="Write Phase 5b optional repeat-annotation planning tables.")
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--preflight-output", type=Path, required=True)
    parser.add_argument("--plan-output", type=Path, required=True)
    parser.add_argument("--provenance-output", type=Path, required=True)
    parser.add_argument("--output-inventory", type=Path, required=True)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    write_phase5b_tables(
        args.config,
        args.preflight_output,
        args.plan_output,
        args.provenance_output,
        args.output_inventory,
    )


if __name__ == "__main__":
    main()
