"""Shared schemas and controlled vocabulary."""

DATA_MANIFEST_COLUMNS = [
    "resource_id",
    "species",
    "accession",
    "source",
    "resource_type",
    "status",
    "size",
    "local_path",
    "source_url",
    "publication_or_resource",
    "usage_notes",
]

SPECIES_MANIFEST_COLUMNS = [
    "species_id",
    "scientific_name",
    "common_name",
    "role",
    "taxon_id",
    "resource_ids",
    "rationale",
    "status",
]

RESOURCE_STATUS_COLUMNS = [
    "resource_id",
    "expected_files",
    "local_path",
    "status",
    "checked_at",
    "message",
]

REFERENCE_FILE_COLUMNS = [
    "resource_id",
    "accession",
    "version",
    "file_role",
    "url",
    "local_path",
    "selected_for_download",
    "download_method",
    "retrieval_date",
    "file_status",
    "byte_size",
    "md5",
    "sha256",
    "notes",
]

LOCAL_FILE_INVENTORY_COLUMNS = [
    "resource_id",
    "source_id",
    "file_name",
    "file_role_candidate",
    "detected_format",
    "local_path",
    "byte_size",
    "md5",
    "sha256",
    "sequence_count",
    "notes",
]

ASSEMBLY_QC_COLUMNS = [
    "resource_id",
    "sequence_count",
    "total_length_bp",
    "n50_bp",
    "gc_percent",
    "n_count",
    "longest_sequence_bp",
    "busco_lineage",
    "busco_complete_percent",
    "busco_single_copy_percent",
    "busco_duplicated_percent",
    "busco_fragmented_percent",
    "busco_missing_percent",
    "notes",
]

REFERENCE_ASSEMBLY_QC_COLUMNS = [
    "resource_id",
    "accession",
    "assembly_name",
    "bioproject",
    "biosample",
    "assembly_level",
    "release_date",
    "source_file",
    "sequence_scope",
    "total_length_bp",
    "ungapped_length_bp",
    "scaffold_count",
    "scaffold_n50_bp",
    "scaffold_l50",
    "contig_count",
    "contig_n50_bp",
    "gc_percent",
    "molecule_count",
    "top_level_count",
    "busco_lineage",
    "busco_complete_percent",
    "notes",
]

PROTEIN_QC_COLUMNS = [
    "resource_id",
    "protein_count",
    "total_aa",
    "mean_length_aa",
    "median_length_aa",
    "duplicate_ids",
    "ambiguous_residue_count",
    "sequences_with_stop_codon",
    "notes",
]

REFERENCE_ANNOTATION_QC_COLUMNS = [
    "resource_id",
    "accession",
    "source_file",
    "protein_coding_gene_count",
    "total_gene_count",
    "separate_gff_url",
    "separate_gff_status",
    "notes",
]

REFERENCE_PROTEIN_QC_COLUMNS = [
    "resource_id",
    "accession",
    "protein_fasta_url",
    "local_path",
    "status",
    "protein_count",
    "total_aa",
    "mean_length_aa",
    "median_length_aa",
    "duplicate_ids",
    "ambiguous_residue_count",
    "sequences_with_stop_codon",
    "notes",
]

PUBLICATION_CLAIM_AUDIT_COLUMNS = [
    "claim_id",
    "publication_id",
    "doi",
    "resource_id",
    "mechanism",
    "gene_or_feature",
    "reported_signal",
    "current_repo_status",
    "evidence_tier",
    "available_supporting_files",
    "blockers",
    "next_validation",
    "interpretation_guardrail",
]

PHASE3_SOURCE_CHECK_COLUMNS = [
    "source_id",
    "resource_id",
    "source_type",
    "url_or_accession",
    "retrieval_date",
    "searched_for",
    "status",
    "found_file_types",
    "selected_for_download",
    "local_path",
    "notes",
]

REFERENCE_GENE_COORDINATE_COLUMNS = [
    "resource_id",
    "accession",
    "gene_id",
    "gene_symbol",
    "seqid",
    "start",
    "end",
    "strand",
    "source_file",
    "parse_status",
    "notes",
]

ORTHOFINDER_INPUT_MANIFEST_COLUMNS = [
    "species_id",
    "resource_id",
    "source_protein_fasta",
    "orthofinder_input_path",
    "protein_set_scope",
    "protein_count",
    "qc_status",
    "orthofinder_ready",
    "blocker",
    "next_action",
    "notes",
]

ORTHOFINDER_PREFLIGHT_COLUMNS = [
    "check_name",
    "status",
    "value",
    "notes",
]

ORTHOGROUP_GENE_COUNT_LONG_COLUMNS = [
    "orthogroup_id",
    "species_id",
    "resource_id",
    "orthofinder_species_column",
    "copy_count",
    "orthofinder_results_dir",
]

ORTHOFINDER_SPECIES_SUMMARY_COLUMNS = [
    "species_id",
    "resource_id",
    "orthofinder_species_column",
    "orthogroups_with_genes",
    "total_gene_copies_in_orthogroups",
    "orthofinder_results_dir",
]

COPY_NUMBER_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "species_id",
    "resource_id",
    "orthogroup_id",
    "copy_count",
    "gene_ids",
    "protein_ids",
    "orthogroup_target_protein_count",
    "orthogroup_species_counts",
    "annotation_match_level",
    "mapping_status",
    "orthofinder_results_dir",
    "resources_supporting",
    "demo_only",
]

DUPLICATION_AUDIT_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "orthogroup_id",
    "copy_count",
    "copy_ids",
    "protein_ids",
    "orthology_support",
    "domain_integrity",
    "separable_loci",
    "coordinate_support",
    "cross_resource_support",
    "isoform_risk",
    "fragmentation_risk",
    "expression_support",
    "annotation_match_level",
    "orthogroup_species_counts",
    "coordinate_summary",
    "mapping_status",
    "orthofinder_results_dir",
    "resources_supporting",
    "artifact_risk",
    "required_validation",
    "demo_only",
]

EVIDENCE_COLUMNS = [
    "mechanism",
    "gene_or_pathway",
    "evidence_type",
    "evidence_tier",
    "resources_supporting",
    "artifact_risk",
    "biological_interpretation",
    "relevance_to_aging_longevity",
    "translational_relevance",
    "required_validation",
    "claim_language_guardrail",
]

CANDIDATE_ISOFORM_AUDIT_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "resource_id",
    "gene_id",
    "orthogroup_id",
    "coordinate_summary",
    "protein_ids",
    "protein_lengths_aa",
    "isoform_count",
    "representative_protein_id",
    "representative_length_aa",
    "representative_fasta_id",
    "selection_method",
    "isoform_filter_status",
    "notes",
]

DOMAIN_CHECK_TARGET_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "resource_id",
    "gene_id",
    "orthogroup_id",
    "representative_protein_id",
    "representative_fasta_id",
    "representative_length_aa",
    "candidate_fasta",
    "domain_check_status",
    "recommended_method",
    "required_validation",
    "notes",
]

RESCUE_TARGET_COLUMNS = [
    "priority",
    "mechanism",
    "gene_symbol",
    "mapping_status",
    "current_copy_count",
    "current_orthogroup_id",
    "aliases_considered",
    "recommended_next_method",
    "required_inputs",
    "blockers",
    "claim_language_guardrail",
    "notes",
]

HMMER_PFAM_PREFLIGHT_COLUMNS = [
    "check_name",
    "status",
    "value",
    "notes",
]

DOMAIN_INTEGRITY_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "resource_id",
    "gene_id",
    "orthogroup_id",
    "representative_protein_id",
    "representative_fasta_id",
    "representative_length_aa",
    "domain_validation_status",
    "best_pfam_accession",
    "best_pfam_name",
    "best_i_evalue",
    "best_bitscore",
    "best_hmm_coverage",
    "best_query_coverage",
    "accepted_domain_count",
    "accepted_domain_accessions",
    "all_domain_hits",
    "hmmer_domtblout",
    "hmmer_database",
    "hmmer_command",
    "classification_rule",
    "claim_language_guardrail",
    "notes",
]

PHASE4_RESCUE_QUERY_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "query_species_id",
    "query_resource_id",
    "query_protein_id",
    "query_description",
    "query_length_aa",
    "source_fasta",
    "selection_status",
    "selection_rule",
    "notes",
]

PHASE4_FORWARD_HIT_COLUMNS = [
    "gene_symbol",
    "query_species_id",
    "query_resource_id",
    "query_protein_id",
    "query_description",
    "query_length_aa",
    "target_species_id",
    "target_resource_id",
    "target_protein_id",
    "target_description",
    "target_length_aa",
    "full_sequence_evalue",
    "full_sequence_bitscore",
    "best_domain_i_evalue",
    "best_domain_bitscore",
    "query_coverage",
    "target_coverage",
    "target_env_from",
    "target_env_to",
    "passes_similarity_filters",
    "filter_rule",
    "notes",
]

PHASE4_RECIPROCAL_HIT_COLUMNS = [
    "gene_symbol",
    "target_protein_id",
    "target_description",
    "target_gene_id",
    "target_coordinate_summary",
    "source_species_id",
    "source_resource_id",
    "query_protein_id",
    "reciprocal_top_protein_id",
    "reciprocal_top_description",
    "reciprocal_top_evalue",
    "reciprocal_top_bitscore",
    "reciprocal_gene_pattern_match",
    "reciprocal_selected_query_match",
    "reciprocal_support_status",
    "notes",
]

PHASE4_RESCUE_SUMMARY_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "initial_mapping_status",
    "query_count",
    "passing_forward_hit_count",
    "reciprocal_supported_hit_count",
    "candidate_gene_ids",
    "candidate_protein_ids",
    "candidate_products",
    "candidate_coordinate_summary",
    "protein_rescue_status",
    "genome_alignment_status",
    "classification",
    "artifact_risk",
    "claim_language_guardrail",
    "required_validation",
    "notes",
]

PHASE4_GENOME_RESCUE_PLAN_COLUMNS = [
    "gene_symbol",
    "recommended_method",
    "genome_fasta",
    "genome_fasta_status",
    "miniprot_status",
    "protein_query_status",
    "run_status",
    "blockers",
    "notes",
]

PHASE4B_PREFLIGHT_COLUMNS = [
    "check_id",
    "resource",
    "path_or_command",
    "status",
    "details",
    "required_for_alignment",
    "notes",
]

PHASE4B_TARGET_REGION_COLUMNS = [
    "gene_symbol",
    "source_coordinate",
    "requested_seqid",
    "target_fasta_header",
    "target_fasta_path",
    "extraction_status",
    "notes",
]

PHASE4B_QUERY_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "query_id",
    "query_source_type",
    "original_protein_id",
    "original_description",
    "source_species_id",
    "source_resource_id",
    "source_fasta",
    "sequence_length_aa",
    "selection_reason",
    "query_status",
    "notes",
]

PHASE4B_ALIGNMENT_HIT_COLUMNS = [
    "gene_symbol",
    "query_id",
    "query_source_type",
    "original_protein_id",
    "source_species_id",
    "source_resource_id",
    "target_seqid",
    "target_start",
    "target_end",
    "strand",
    "feature_id",
    "feature_type",
    "query_start",
    "query_end",
    "query_length_aa",
    "query_coverage",
    "cds_feature_count",
    "exon_feature_count",
    "frameshift_or_stop_flag",
    "identity",
    "positive",
    "score",
    "rank",
    "alignment_status",
    "raw_attributes",
    "notes",
]

PHASE4B_SUMMARY_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "protein_rescue_status",
    "query_count",
    "alignment_hit_count",
    "high_coverage_hit_count",
    "separable_high_coverage_loci",
    "best_query_coverage",
    "candidate_loci",
    "genome_validation_status",
    "candidate_classification",
    "artifact_risk",
    "claim_language_guardrail",
    "required_validation",
    "notes",
]

PHASE4C_LOCUS_REVIEW_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "locus_cluster_id",
    "target_seqid",
    "requested_scaffold_aliases",
    "cluster_start",
    "cluster_end",
    "strand_values",
    "supporting_query_count",
    "supporting_query_ids",
    "supporting_original_protein_ids",
    "best_query_coverage",
    "best_identity",
    "hit_count",
    "high_coverage_hit_count",
    "cds_feature_count_range",
    "exon_feature_count_range",
    "paf_frameshift_count",
    "paf_stop_count",
    "miniprot_disruption_status",
    "domain_validation_status",
    "domain_supported_query_count",
    "best_domain_hits",
    "overlap_cluster_size",
    "overlap_note",
    "candidate_locus_status",
    "artifact_risk",
    "claim_language_guardrail",
    "required_validation",
    "notes",
]

PHASE4C_GENE_REVIEW_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "reviewed_locus_count",
    "high_coverage_locus_count",
    "domain_supported_locus_count",
    "loci_with_disruption_flags",
    "best_query_coverage",
    "candidate_loci",
    "phase4c_status",
    "artifact_risk",
    "claim_language_guardrail",
    "required_validation",
    "notes",
]

PHASE4C_TP53_CHUNK_PLAN_COLUMNS = [
    "chunk_id",
    "chunk_fasta",
    "sequence_count",
    "total_bases",
    "target_seqids",
    "run_status",
    "stderr_log",
    "raw_gff",
    "notes",
]

PHASE4C_TP53_TARGET_REGION_COLUMNS = [
    "gene_symbol",
    "source_table",
    "source_protein_id",
    "source_description",
    "source_coordinate",
    "requested_seqid",
    "target_fasta_header",
    "target_fasta_path",
    "extraction_status",
    "notes",
]

PHASE4C_TP53_SUMMARY_COLUMNS = [
    "gene_symbol",
    "query_id",
    "query_source_type",
    "query_length_aa",
    "search_scope",
    "chunks_scanned",
    "total_bases_scanned",
    "alignment_hit_count",
    "high_coverage_hit_count",
    "partial_hit_count",
    "best_query_coverage",
    "candidate_loci",
    "genome_search_status",
    "candidate_classification",
    "artifact_risk",
    "claim_language_guardrail",
    "required_validation",
    "notes",
]

PHASE4D_CANDIDATE_INTERPRETATION_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "phase4d_status",
    "evidence_type",
    "evidence_tier",
    "phase4_sources",
    "candidate_loci",
    "reviewed_locus_count",
    "high_coverage_locus_count",
    "domain_supported_locus_count",
    "loci_with_disruption_flags",
    "best_query_coverage",
    "artifact_risk",
    "conservative_interpretation",
    "relevance_to_aging_longevity",
    "copy_number_interpretation_status",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
    "next_action",
    "notes",
]

PHASE4E_LOCUS_HARDENING_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "locus_cluster_id",
    "target_seqid",
    "annotation_seqid",
    "locus_start",
    "locus_end",
    "locus_span_bp",
    "strand_values",
    "same_gene_locus_order",
    "nearest_same_gene_locus_distance_bp",
    "supporting_query_count",
    "supporting_query_ids",
    "supporting_original_protein_ids",
    "best_query_coverage",
    "best_identity",
    "cds_feature_count_range",
    "miniprot_frameshift_count",
    "miniprot_stop_count",
    "miniprot_disruption_status",
    "domain_validation_status",
    "best_domain_hits",
    "annotation_overlap_status",
    "overlapping_gene_count",
    "overlapping_gene_ids",
    "overlapping_locus_tags",
    "overlapping_products",
    "focal_annotation_overlap",
    "annotation_product_consistency",
    "annotation_overlap_fraction",
    "gene_family_artifact_risk",
    "phase4e_locus_status",
    "artifact_flags",
    "hardened_interpretation",
    "manual_review_priority",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE4E_GENE_HARDENING_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "reviewed_locus_count",
    "focal_annotation_overlap_count",
    "product_consistent_annotation_overlap_count",
    "domain_supported_locus_count",
    "no_disruption_locus_count",
    "disruption_flag_locus_count",
    "distinct_annotation_seqids",
    "min_inter_locus_distance_bp",
    "clustered_same_scaffold",
    "phase4e_hardened_status",
    "evidence_tier_recommendation",
    "artifact_risk",
    "copy_number_interpretation_status",
    "conservative_interpretation",
    "next_action",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE5_REPEAT_RESOURCE_COLUMNS = [
    "resource_id",
    "source_id",
    "file_name",
    "file_role_candidate",
    "detected_format",
    "local_path",
    "byte_size",
    "repeat_annotation_status",
    "repeat_feature_count",
    "inspection_method",
    "notes",
]

PHASE5_REPEAT_FEATURE_COLUMNS = [
    "repeat_id",
    "seqid",
    "start",
    "end",
    "strand",
    "repeat_class",
    "repeat_family",
    "repeat_name",
    "source_file",
    "parse_status",
    "notes",
]

PHASE5_LOCUS_REPEAT_CONTEXT_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "locus_cluster_id",
    "annotation_seqid",
    "locus_start",
    "locus_end",
    "locus_span_bp",
    "window_start",
    "window_end",
    "window_size_bp",
    "repeat_annotation_status",
    "repeat_overlap_count",
    "repeat_overlap_bp",
    "repeat_overlap_fraction",
    "nearest_repeat_distance_bp",
    "repeat_classes",
    "repeat_families",
    "repeat_names",
    "artifact_context_status",
    "biological_interpretation",
    "claim_language_guardrail",
    "required_validation",
    "supporting_files",
]

PHASE5_GENE_REPEAT_CONTEXT_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "locus_count",
    "annotation_seqids",
    "cluster_start",
    "cluster_end",
    "repeat_annotation_status",
    "loci_with_repeat_overlap",
    "total_repeat_overlap_bp",
    "max_locus_repeat_overlap_fraction",
    "repeat_classes",
    "repeat_families",
    "phase5_context_status",
    "artifact_risk",
    "conservative_interpretation",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE5B_PREFLIGHT_COLUMNS = [
    "check_id",
    "resource",
    "path_or_setting",
    "status",
    "required_for",
    "details",
    "notes",
]

PHASE5B_PLAN_COLUMNS = [
    "step_id",
    "step_name",
    "recommended_environment",
    "command_template",
    "expected_output",
    "run_status",
    "notes",
]

PHASE5B_PROVENANCE_COLUMNS = [
    "field",
    "value",
    "status",
    "notes",
]

PHASE5B_OUTPUT_INVENTORY_COLUMNS = [
    "output_id",
    "file_role",
    "local_path",
    "status",
    "byte_size",
    "md5",
    "sha256",
    "recommended_for_phase5_import",
    "notes",
]

PHASE5C_INTEGRITY_COLUMNS = [
    "check_id",
    "file_role",
    "path",
    "status",
    "byte_size",
    "phase5b_inventory_status",
    "phase5b_inventory_sha256",
    "log_warning_status",
    "candidate_context_usability",
    "notes",
]

PHASE5C_LOCUS_QC_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "locus_cluster_id",
    "annotation_seqid",
    "locus_start",
    "locus_end",
    "window_start",
    "window_end",
    "window_size_bp",
    "gff_repeat_overlap_count",
    "gff_repeat_overlap_fraction",
    "repeatmasker_out_overlap_count",
    "repeatmasker_out_overlap_bp",
    "repeatmasker_out_overlap_fraction",
    "repeatmasker_out_window_repeat_bp",
    "repeatmasker_out_window_repeat_density",
    "repeatmasker_out_classes",
    "repeatmasker_out_families",
    "repeatmasker_out_names",
    "gff_out_overlap_concordance",
    "qc_context_status",
    "artifact_risk_modifier",
    "interpretation_guardrail",
    "required_validation",
    "supporting_files",
]

PHASE5C_GENE_QC_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "locus_count",
    "annotation_seqids",
    "gff_loci_with_direct_overlap",
    "repeatmasker_out_loci_with_direct_overlap",
    "max_repeatmasker_out_overlap_fraction",
    "max_window_repeat_density",
    "repeatmasker_out_classes",
    "repeatmasker_out_families",
    "gff_out_concordance_summary",
    "phase5c_qc_status",
    "artifact_risk_modifier",
    "conservative_interpretation",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE6_TELOMERE_MOTIF_SCAN_COLUMNS = [
    "resource_id",
    "genome_fasta",
    "sequence_id",
    "sequence_length_bp",
    "terminal_window_bp",
    "effective_terminal_window_bp",
    "left_TTAGGG_count",
    "left_CCCTAA_count",
    "right_TTAGGG_count",
    "right_CCCTAA_count",
    "left_control_TTAGGG_count",
    "left_control_CCCTAA_count",
    "right_control_TTAGGG_count",
    "right_control_CCCTAA_count",
    "terminal_total_motif_count",
    "control_total_motif_count",
    "terminal_motif_density_per_kb",
    "control_motif_density_per_kb",
    "end_enrichment_ratio",
    "motif_scan_status",
    "interpretation_guardrail",
]

PHASE6_SCAFFOLD_END_ENRICHMENT_COLUMNS = [
    "resource_id",
    "genome_fasta",
    "motifs",
    "terminal_window_bp",
    "sequence_count_scanned",
    "total_terminal_bp_scanned",
    "total_control_bp_scanned",
    "terminal_total_motif_count",
    "control_total_motif_count",
    "terminal_motif_density_per_kb",
    "control_motif_density_per_kb",
    "end_enrichment_ratio",
    "scaffolds_with_terminal_motif",
    "scaffolds_with_terminal_motif_fraction",
    "scaffolds_with_terminal_enrichment_gt_1",
    "motif_scan_status",
    "biological_interpretation",
    "claim_language_guardrail",
    "required_validation",
    "supporting_files",
]

PHASE6_TELOMERE_GENE_AUDIT_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "synonyms",
    "panel_status",
    "copy_number_mapping_status",
    "copy_count",
    "orthogroup_id",
    "resources_supporting",
    "duplication_artifact_risk",
    "integrated_evidence_tier",
    "integrated_artifact_risk",
    "readiness_status",
    "conservative_interpretation",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7_RNASEQ_MANIFEST_COLUMNS = [
    "resource_id",
    "bioproject",
    "sra_study",
    "experiment",
    "run",
    "biosample",
    "sample",
    "sample_name",
    "scientific_name",
    "taxon_id",
    "sex",
    "tissue",
    "library_strategy",
    "library_source",
    "library_selection",
    "library_layout",
    "platform",
    "model",
    "spots",
    "bases",
    "avg_length",
    "size_mb",
    "release_date",
    "load_date",
    "download_path",
    "source_url",
    "retrieval_date",
    "local_path",
    "download_status",
    "metadata_status",
    "usage_notes",
]

PHASE7_RNASEQ_READINESS_COLUMNS = [
    "resource_id",
    "run",
    "experiment",
    "biosample",
    "sample_name",
    "tissue",
    "library_strategy",
    "library_source",
    "library_selection",
    "library_layout",
    "platform_model",
    "spots",
    "bases",
    "size_mb",
    "metadata_status",
    "expression_readiness_status",
    "included_for_candidate_expression_plan",
    "exclusion_reason",
    "artifact_or_design_risk",
    "conservative_interpretation",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7_CANDIDATE_EXPRESSION_PLAN_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "synonyms",
    "rnaseq_resource_id",
    "usable_rnaseq_run_count",
    "usable_experiments",
    "usable_biosamples",
    "usable_tissues",
    "candidate_panel_status",
    "planned_quantification_scope",
    "recommended_future_method",
    "current_expression_status",
    "design_limitations",
    "conservative_interpretation",
    "required_inputs",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7B_REFERENCE_STRATEGY_COLUMNS = [
    "strategy_id",
    "strategy_role",
    "recommended_tool_or_method",
    "algorithm_class",
    "required_inputs",
    "local_inputs_available",
    "planned_output",
    "readiness_status",
    "rationale",
    "limitations",
    "claim_language_guardrail",
    "next_action",
]

PHASE7B_CANDIDATE_QUANT_MAP_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "phase7a_current_expression_status",
    "phase7a_usable_run_count",
    "phase7a_usable_tissues",
    "exact_annotation_gene_ids",
    "phase4e_candidate_gene_ids",
    "quantification_gene_ids",
    "cds_reference_sequence_ids",
    "transcript_or_cds_count",
    "representative_protein_ids",
    "isoform_count",
    "orthology_mapping_status",
    "phase4e_status",
    "artifact_or_ambiguity_risk",
    "quantification_strategy_status",
    "recommended_quantification_scope",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7B_RUN_PLAN_COLUMNS = [
    "step_id",
    "step_name",
    "recommended_environment",
    "command_template",
    "expected_output",
    "run_status",
    "notes",
]

PHASE7C_TX2GENE_COLUMNS = [
    "transcript_id",
    "gene_id",
    "gene_symbol",
    "locus_tag",
    "scaffold",
    "strand",
    "feature_type",
    "exon_count",
    "transcript_length_bp",
    "reference_status",
]

PHASE7C_REFERENCE_QC_COLUMNS = [
    "reference_id",
    "annotation_gff",
    "genome_fasta",
    "transcript_fasta",
    "tx2gene",
    "transcript_count",
    "gene_count",
    "exon_derived_transcript_count",
    "cds_fallback_transcript_count",
    "missing_scaffold_count",
    "zero_length_transcript_count",
    "total_transcript_bp",
    "median_transcript_length_bp",
    "candidate_quant_map_rows",
    "validation_status",
    "construction_method",
    "limitations",
    "claim_language_guardrail",
]

PHASE7C_CANDIDATE_REFERENCE_VALIDATION_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "phase7b_quantification_strategy_status",
    "quantification_gene_ids",
    "matched_gene_ids",
    "matched_transcript_ids",
    "matched_transcript_count",
    "total_matched_transcript_bp",
    "reference_mapping_status",
    "ambiguity_status",
    "phase7c_quantification_readiness",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7D_RAW_READ_INTAKE_COLUMNS = [
    "resource_id",
    "run",
    "experiment",
    "biosample",
    "sample_name",
    "tissue",
    "library_layout",
    "read1_path",
    "read2_path",
    "read1_status",
    "read2_status",
    "read1_size_bytes",
    "read2_size_bytes",
    "raw_pair_status",
    "md5_status",
    "intake_status",
    "required_action",
]

PHASE7D_FASTQ_QC_COLUMNS = [
    "run",
    "read",
    "fastq_path",
    "file_status",
    "records_inspected",
    "mean_read_length",
    "gc_percent",
    "n_percent",
    "mean_phred_quality",
    "qc_status",
    "notes",
]

PHASE7D_SALMON_PREFLIGHT_COLUMNS = [
    "check_id",
    "item",
    "path_or_value",
    "status",
    "message",
    "required_action",
]

PHASE7D_SALMON_QUANT_SUMMARY_COLUMNS = [
    "run",
    "tissue",
    "read1_path",
    "read2_path",
    "salmon_output_dir",
    "quant_sf",
    "quantification_status",
    "salmon_command",
    "log_stdout",
    "log_stderr",
    "message",
]

PHASE7D_CANDIDATE_EXPRESSION_MATRIX_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "run",
    "tissue",
    "phase7c_quantification_readiness",
    "matched_transcript_count",
    "quantified_transcript_count",
    "summed_tpm",
    "summed_numreads",
    "candidate_expression_status",
    "quantification_status",
    "conservative_interpretation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7E_RUN_QC_COLUMNS = [
    "run",
    "tissue",
    "quantification_status",
    "fastq_qc_status",
    "fastq_files_reviewed",
    "records_inspected_per_read",
    "mean_read_length_range",
    "min_mean_phred_quality",
    "max_n_percent",
    "salmon_num_processed",
    "salmon_num_mapped",
    "salmon_percent_mapped",
    "salmon_library_types",
    "salmon_decoy_count",
    "mapping_rate_status",
    "interpretation_use_status",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7E_CANDIDATE_HARDENED_COLUMNS = [
    "mechanism",
    "gene_symbol",
    "tissue",
    "quantified_run_count",
    "detected_run_count",
    "not_detected_run_count",
    "locus_review_run_count",
    "detected_runs",
    "median_tpm",
    "min_tpm",
    "max_tpm",
    "median_numreads",
    "phase7c_quantification_readiness",
    "reference_mapping_status",
    "reference_ambiguity_status",
    "matched_transcript_count",
    "orthology_mapping_status",
    "duplication_artifact_risk",
    "phase4e_hardened_status",
    "phase4e_artifact_risk",
    "phase5c_artifact_risk_modifier",
    "low_mapping_run_count",
    "very_low_mapping_run_count",
    "min_run_mapping_rate",
    "expression_interpretation_status",
    "phase7e_expression_support_level",
    "artifact_risk",
    "conservative_interpretation",
    "required_validation",
    "claim_language_guardrail",
    "supporting_files",
]

PHASE7E_PARAMETER_REVIEW_COLUMNS = [
    "parameter",
    "configured_value",
    "observed_value",
    "review_status",
    "technical_rationale",
    "scientific_guardrail",
    "recommended_action",
]

PHASE8A_INTEGRATION_AUDIT_COLUMNS = [
    "gene_symbol",
    "base_evidence_tier",
    "expression_evidence_tier",
    "integrated_evidence_tier",
    "tier_change",
    "phase7e_expression_support_level",
    "expression_interpretation_status",
    "integration_action",
    "expression_support_used",
    "artifact_risk_update",
    "required_validation_update",
    "supporting_files",
]

PHASE8B_TIER_AUDIT_COLUMNS = [
    "gene_symbol",
    "mechanism",
    "current_evidence_tier",
    "phase8b_final_evidence_tier",
    "tier_change",
    "phase8b_audit_status",
    "phase8b_reporting_class",
    "evidence_components",
    "orthology_component",
    "locus_component",
    "repeat_context_component",
    "telomere_component",
    "expression_component",
    "artifact_risk_level",
    "major_caveats",
    "required_validation",
    "supporting_files",
    "claim_language_guardrail",
]

PHASE8B_MECHANISM_SUMMARY_COLUMNS = [
    "mechanism",
    "candidate_count",
    "tier1_count",
    "tier2_count",
    "tier3_count",
    "artifact_uncertain_count",
    "robust_ready_count",
    "plausible_lead_count",
    "exploratory_count",
    "artifact_prone_count",
    "expression_supported_count",
    "repeat_context_caveat_count",
    "locus_review_required_count",
    "required_validation",
]

PHASE9_FIGURE_MANIFEST_COLUMNS = [
    "figure_id",
    "title",
    "figure_type",
    "source_table",
    "figure_data",
    "output_svg",
    "status",
    "interpretation_guardrail",
]

PHASE9_KEY_FINDINGS_COLUMNS = [
    "finding_id",
    "question",
    "answer",
    "supporting_files",
    "interpretation_guardrail",
]

PHASE9_PACKAGE_AUDIT_COLUMNS = [
    "audit_id",
    "audit_area",
    "item",
    "source",
    "status",
    "evidence",
    "required_action",
]

PHASE9_RELEASE_READINESS_COLUMNS = [
    "check_id",
    "readiness_area",
    "item",
    "status",
    "evidence",
    "required_action",
]

ALLOWED_STATUSES = {
    "REGISTERED",
    "LOCAL_AVAILABLE",
    "MISSING_LOCAL",
    "NOT_ASSESSED",
    "DEMO_ONLY",
}

ALLOWED_TIERS = {"Tier 1", "Tier 2", "Tier 3", "Artifact/uncertain"}

ALLOWED_MECHANISMS = {
    "Resource quality and provenance",
    "DNA repair/genome stability",
    "p53 pathway",
    "Chromatin and epigenome-related regulation",
    "Telomere-related biology",
    "Ferroptosis, iron handling, and oxidative stress",
    "Antioxidant response",
    "Mitochondrial biology and metabolism",
    "Immune and inflammatory regulation",
    "Proteostasis and autophagy",
    "Tissue-specific preservation",
    "Population history",
}

GUARDRAIL_TERMS = ["activated", "inactivated", "absent", "causes", "proves"]
